language: scala
jdk: oraclejdk7
sudo: false
scala:
  - 2.11.1
addons:
  postgresql: "9.3"
env:
  - DATABASE_URL=jdbc:postgresql:loglist?user=postgres
    APPLY_EVOLUTIONS_SILENTLY=true
    RECAPTCHA_PUBLIC_KEY=horta
    RECAPTCHA_PRIVATE_KEY=horta
    BASIC_AUTH_USERNAME=horta
    BASIC_AUTH_PASSWORD=hell
    APPROVAL_SMTP_HOST="smtp.loglist.xyz"
    APPROVAL_EMAIL="noreply@loglist.xyz"
    APPROVAL_EMAIL_PASSWORD="hortahell"
before_script:
  - psql -c 'create database loglist;' -U postgres
  - psql -c 'create extension pgcrypto;' -U postgres -d loglist
script:
  - sbt -jvm-opts compile test
notifications:
  email:
    - reximkut@gmail.com